name: hi_farm
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  ionicons: ^0.2.2
  google_fonts: ^5.1.0
  iconsax: ^0.0.8
  form_field_validator:
  flutter_svg:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  dotted_border: ^2.1.0
  webview_flutter: ^4.2.2


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/
    - assets/images/
    - assets/

    - assets/icon/
    - assets/logo/
